# This file contains human readable experiment descriptions for ClimateDT simulations.

experiment_description:
  "climatedt-gen2/IFS-FESOM-10km/story-nudging-Tplus2K/r1/": "The Storyline Tplus2K description goes here",
  "climatedt-gen2/IFS-FESOM-10km/story-nudging-cont/r1/": "The Storyline control description goes here",
  "climatedt-gen2/IFS-FESOM-10km/story-nudging-hist/r1/": "The Storyline historical description goes here",
  "climatedt-gen2/ICON-5km/baseline-cont/r1/": "The ICON control description goes here",
  "climatedt-gen2/ICON-5km/baseline-hist/r1/": "The ICON historical description goes here",
  "climatedt-gen2/ICON-5km/projections-ssp370/r1/": "The ICON SSP370 projection description goes here",
  "climatedt-gen2/IFS-FESOM-5km/baseline-cont/r1/": "The IFS-FESOM control description goes here",
  "climatedt-gen2/IFS-FESOM-5km/baseline-hist/r1/": "The IFS-FESOM historical description goes here",
  "climatedt-gen2/IFS-FESOM-5km/projections-ssp370/r1/": "The IFS-FESOM SSP370 projection description goes here",
  "climatedt-gen2/IFS-NEMO-5km/baseline-cont/r1/": "The IFS-NEMO control description goes here",
  "climatedt-gen2/IFS-NEMO-5km/baseline-hist/r1/": "The IFS-NEMO historical description goes here",
  "climatedt-gen2/IFS-NEMO-5km/projections-ssp370/r1/": "The IFS-NEMO SSP370 projection description goes here"
