# Dev environment overrides.
# Keys here are deep-merged on top of common.yaml by the signer service.
# Use this to hide diagnostics, override descriptions, etc. for the dev dashboard.
#
# See README.md for the full reference of supported keys.

hide:
  diagnostics:
    - "Sea Ice":
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-cont/r1"
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-hist/r1"
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-Tplus2K/r1"
    - "Ocean 2D":
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-cont/r1"
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-hist/r1"
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-Tplus2K/r1"
    - "Ocean 3D":
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-cont/r1"
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-hist/r1"
        - "climatedt-gen2/IFS-FESOM-10km/story-nudging-Tplus2K/r1"
        
  
